<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-10-20 08:51
=======
# Generated by Django 5.1.2 on 2024-10-27 06:04
>>>>>>> develop

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=20)),
                ('meal_choices', models.CharField(max_length=50)),
                ('birth_year', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('muscle', models.FloatField(blank=True, null=True)),
                ('body_fat_percent', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
