# Generated by Django 5.1.2 on 2024-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='exercise_regular',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='intensity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lifestyle',
            field=models.CharField(default='desk_job', max_length=15),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sleep_duration',
            field=models.CharField(default='7_8', max_length=10),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
