# Generated by Django 5.1.2 on 2024-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_exercise_regular_userinfo_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='exercise_regular',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lifestyle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sleep_duration',
            field=models.CharField(max_length=10),
        ),
    ]
